kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: rancher/dapper:v0.4.1
    environment:
      GIT_IN_DAPPER: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - apk add --no-cache git
      - apk add --no-cache bash
      - echo $PWD
      - ./scripts/rancher-prepare dapper ci
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock